services:
  db:
    image: postgres:16-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: buddyscript
      POSTGRES_PASSWORD: buddyscript
      POSTGRES_DB: buddyscript
    volumes:
      - buddyscript:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data

volumes:
  buddyscript:
  miniodata:
